# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: 'Build my-app'
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'asdemoacr'
            repository: 'api/my-app'
            command: 'buildAndPush'
            Dockerfile: 'src/Dockerfile'
            buildContext: 'src/.'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'k8s'
            artifact: 'manifest'
            publishLocation: 'pipeline'

  - stage: DeployTest
    displayName: 'Deploy to TEST'
    dependsOn: Build
    variables:
      namespace: test
    jobs:
      - deployment: DeployTest
        displayName: 'Deploy to TEST'
        pool:
          vmImage: ubuntu-latest
        environment: my-app-test
        strategy:
         runOnce:
           deploy:
             steps:
               - task: CmdLine@2
                 inputs:
                   script: 'printenv'
               - task: DownloadPipelineArtifact@2
                 inputs:
                   buildType: 'current'
                   artifactName: 'manifest'
                   targetPath: '$(Pipeline.Workspace)'
               - task: CmdLine@2
                 inputs:
                   script: 'ls -la $(Pipeline.Workspace)'
               - task: KubernetesManifest@1
                 name: bake
                 inputs:
                   action: 'bake'
                   containers: 'asdemoacr.azurecr.io/api/my-app:$(Build.BuildId)'
                   renderType: 'kustomize'
                   kustomizationPath: '$(Pipeline.Workspace)/test'
                   namespace: '$(namespace)'
               - task: KubernetesManifest@1
                 inputs:
                   action: 'deploy'
                   connectionType: 'kubernetesServiceConnection'
                   kubernetesServiceConnection: 'my-app-test-as-test-1686907435574'
                   namespace: '$(namespace)'
                   manifests: '$(bake.manifestsBundle)'
                   rolloutStatusTimeout: '120'
              
  - stage: DeployProd
    displayName: 'Deploy to PROD'
    dependsOn: DeployTest
    variables:
      namespace: prod
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy to PROD'
        pool:
          vmImage: ubuntu-latest
        environment: my-app-prod
        strategy:
         runOnce:
           deploy:
             steps:
               - task: CmdLine@2
                 inputs:
                   script: 'printenv'
               - task: DownloadPipelineArtifact@2
                 inputs:
                   buildType: 'current'
                   artifactName: 'manifest'
                   targetPath: '$(Pipeline.Workspace)'
               - task: CmdLine@2
                 inputs:
                   script: 'ls -la $(Pipeline.Workspace)'
               - task: KubernetesManifest@1
                 name: bake
                 inputs:
                   action: 'bake'
                   containers: 'asdemoacr.azurecr.io/api/my-app:$(Build.BuildId)'
                   renderType: 'kustomize'
                   kustomizationPath: '$(Pipeline.Workspace)/prod'
                   namespace: '$(namespace)'
               - task: KubernetesManifest@1
                 inputs:
                   action: 'deploy'
                   connectionType: 'kubernetesServiceConnection'
                   kubernetesServiceConnection: 'my-app-prod-as-prod-1686907474780'
                   namespace: '$(namespace)'
                   manifests: '$(bake.manifestsBundle)'
                   rolloutStatusTimeout: '120'
              