# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: 'Build my-app'
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'asdemoacr'
            repository: 'api/my-app'
            command: 'buildAndPush'
            Dockerfile: 'src/Dockerfile'
            buildContext: 'src/.'

  - stage: DeployTest
    displayName: 'Deploy to TEST'
    dependsOn: Build
    jobs:
      - deployment: DeployTest
        displayName: 'Deploy to TEST'
        pool:
          vmImage: ubuntu-latest
        environment: my-app-test
        strategy:
         runOnce:
           deploy:
             steps:
               - task: CmdLine@2
                 inputs:
                   script: 'printenv'
               - task: KubernetesManifest@1
                 inputs:
                   action: 'deploy'
                   connectionType: 'kubernetesServiceConnection'
                   kubernetesServiceConnection: 'my-app-test-as-test-1686907435574'
                   namespace: 'test'
                   manifests: 'k8s/my-app.yaml'
                   containers: 'asdemoacr.azurecr.io/api/my-app:$(Build.BuildId)'
                   rolloutStatusTimeout: '120'
              



