apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
configMapGenerator:
- name: my-app-config
  files:
  - appsettings.json