apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    env:
    - name: NAME
      value: "Kubernetes Up and Running!"
    - name: FOO
      value: "BAR"
    resources: {}