apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  NAME: "Kubernetes Up and Running!"
  FOO: "BAR"
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    envFrom:
    - configMapRef:
        name: myapp-config
    env:
    - name: NAME_DEMO
      valueFrom:
        configMapKeyRef:
          name: myapp-config
          key: NAME
    resources: {}
